name: Recipick Frontend "admin" Develop CI/CD

on:
  push:
    branches: [ dev ]
    paths:
      - 'apps/admin/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'apps/admin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: admin-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build admin app
        run: pnpm --filter admin build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/admin
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-admin:dev
            ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-admin:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    environment: admin-dev
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop recipick-frontend-admin || true
            docker rm recipick-frontend-admin || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-admin:dev
            docker run -d \
              --name recipick-frontend-admin \
              -p ${{ vars.APP_PORT }}:80 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-admin:dev