name: Recipick Frontend "user" Product CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/user/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/user/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: user-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build user app
        run: pnpm --filter user build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/user
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-user:prod
            ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-user:prod-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    environment: user-prod
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop recipick-frontend-user || true
            docker rm recipick-frontend-user || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-user:prod
            docker run -d \
              --name recipick-frontend-user \
              -p ${{ env.APP_PORT }}:80 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/recipick-frontend-user:prod